ALTER TABLE transactions 
MODIFY COLUMN amount DECIMAL(12,2),
MODIFY COLUMN tax DECIMAL(10,2),
MODIFY COLUMN serviceFee DECIMAL(10,2),
MODIFY COLUMN discount DECIMAL(10,2),
MODIFY COLUMN otherCharge DECIMAL(10,2);
